# Makefile for GCC/Mingw32 cross-compiled from linux

PREFIX=i386-mingw32crt-

all:
	make -f makefile.mingw32 PATHSEP=/ \
            AR=$(PREFIX)ar RANLIB=$(PREFIX)ranlib \
		    STRIP=$(PREFIX)strip \
            LD=$(PREFIX)ld CC=$(PREFIX)gcc all

wrapper:
	make -f makefile.mingw32 PATHSEP=/ \
            AR=$(PREFIX)ar RANLIB=$(PREFIX)ranlib \
		    STRIP=$(PREFIX)strip \
            LD=$(PREFIX)ld CC=$(PREFIX)gcc wrapper

clean:
	make -f makefile.mingw32 PATHSEP=/ clean
