extern _MultinetGetConnectionPerformanceW@8
export MultinetGetConnectionPerformanceW@8
extern _WNetAddConnection2W@16
export WNetAddConnection2W@16
extern _WNetAddConnection3W@20
export WNetAddConnection3W@20
extern _WNetAddConnectionW@12
export WNetAddConnectionW@12
extern _WNetCancelConnection2W@12
export WNetCancelConnection2W@12
extern _WNetCancelConnectionW@8
export WNetCancelConnectionW@8
extern _WNetConnectionDialog1W@4
export WNetConnectionDialog1W@4
extern _WNetDisconnectDialog1W@4
export WNetDisconnectDialog1W@4
extern _WNetEnumResourceW@16
export WNetEnumResourceW@16
extern _WNetGetConnectionW@12
export WNetGetConnectionW@12
extern _WNetGetLastErrorW@20
export WNetGetLastErrorW@20
extern _WNetGetNetworkInformationW@8
export WNetGetNetworkInformationW@8
extern _WNetGetProviderNameW@12
export WNetGetProviderNameW@12
extern _WNetGetResourceInformationW@16
export WNetGetResourceInformationW@16
extern _WNetGetResourceParentW@12
export WNetGetResourceParentW@12
extern _WNetGetUniversalNameW@16
export WNetGetUniversalNameW@16
extern _WNetGetUserW@12
export WNetGetUserW@12
extern _WNetOpenEnumW@20
export WNetOpenEnumW@20
extern _WNetUseConnectionW@32
export WNetUseConnectionW@32
extern _AddFontResourceW@4
export AddFontResourceW@4
extern _CopyEnhMetaFileW@8
export CopyEnhMetaFileW@8
extern _CopyMetaFileW@8
export CopyMetaFileW@8
extern _CreateColorSpaceW@4
export CreateColorSpaceW@4
extern _CreateDCW@16
export CreateDCW@16
extern _CreateEnhMetaFileW@16
export CreateEnhMetaFileW@16
extern _CreateFontIndirectW@4
export CreateFontIndirectW@4
extern _CreateFontW@56
export CreateFontW@56
extern _CreateICW@16
export CreateICW@16
extern _CreateMetaFileW@4
export CreateMetaFileW@4
extern _CreateScalableFontResourceW@16
export CreateScalableFontResourceW@16
extern _EnumFontFamiliesExW@20
export EnumFontFamiliesExW@20
extern _EnumFontFamiliesW@16
export EnumFontFamiliesW@16
extern _EnumFontsW@16
export EnumFontsW@16
extern _EnumICMProfilesW@12
export EnumICMProfilesW@12
extern _ExtTextOutW@32
export ExtTextOutW@32
extern _GetCharABCWidthsFloatW@16
export GetCharABCWidthsFloatW@16
extern _GetCharABCWidthsW@16
export GetCharABCWidthsW@16
extern _GetCharWidthFloatW@16
export GetCharWidthFloatW@16
extern _GetCharWidthW@16
export GetCharWidthW@16
extern _GetCharWidth32W@16
export GetCharWidth32W@16
extern _GetCharacterPlacementW@24
export GetCharacterPlacementW@24
extern _GetEnhMetaFileDescriptionW@12
export GetEnhMetaFileDescriptionW@12
extern _GetEnhMetaFileW@4
export GetEnhMetaFileW@4
extern _GetGlyphOutlineW@28
export GetGlyphOutlineW@28
extern _GetICMProfileW@12
export GetICMProfileW@12
extern _GetKerningPairsW@12
export GetKerningPairsW@12
extern _GetLogColorSpaceW@12
export GetLogColorSpaceW@12
extern _GetMetaFileW@4
export GetMetaFileW@4
extern _GetObjectW@12
export GetObjectW@12
extern _GetOutlineTextMetricsW@12
export GetOutlineTextMetricsW@12
extern _GetTextExtentExPointW@28
export GetTextExtentExPointW@28
extern _GetTextExtentPoint32W@16
export GetTextExtentPoint32W@16
extern _GetTextExtentPointW@16
export GetTextExtentPointW@16
extern _GetTextFaceW@12
export GetTextFaceW@12
extern _GetTextMetricsW@8
export GetTextMetricsW@8
extern _PolyTextOutW@12
export PolyTextOutW@12
extern _RemoveFontResourceW@4
export RemoveFontResourceW@4
extern _ResetDCW@8
export ResetDCW@8
extern _SetICMProfileW@8
export SetICMProfileW@8
extern _StartDocW@8
export StartDocW@8
extern _TextOutW@20
export TextOutW@20
extern _UpdateICMRegKeyW@16
export UpdateICMRegKeyW@16
extern _PlaySoundW@12
export PlaySoundW@12
extern _auxGetDevCapsW@12
export auxGetDevCapsW@12
extern _joyGetDevCapsW@12
export joyGetDevCapsW@12
extern _mciGetDeviceIDW@4
export mciGetDeviceIDW@4
extern _mciGetErrorStringW@12
export mciGetErrorStringW@12
extern _mciSendCommandW@16
export mciSendCommandW@16
extern _mciSendStringW@16
export mciSendStringW@16
extern _midiInGetDevCapsW@12
export midiInGetDevCapsW@12
extern _midiInGetErrorTextW@12
export midiInGetErrorTextW@12
extern _midiOutGetDevCapsW@12
export midiOutGetDevCapsW@12
extern _midiOutGetErrorTextW@12
export midiOutGetErrorTextW@12
extern _mixerGetControlDetailsW@12
export mixerGetControlDetailsW@12
extern _mixerGetDevCapsW@12
export mixerGetDevCapsW@12
extern _mixerGetLineControlsW@12
export mixerGetLineControlsW@12
extern _mixerGetLineInfoW@12
export mixerGetLineInfoW@12
extern _mmioInstallIOProcW@12
export mmioInstallIOProcW@12
extern _mmioOpenW@12
export mmioOpenW@12
extern _mmioRenameW@16
export mmioRenameW@16
extern _mmioStringToFOURCCW@8
export mmioStringToFOURCCW@8
extern _sndPlaySoundW@8
export sndPlaySoundW@8
extern _waveInGetDevCapsW@12
export waveInGetDevCapsW@12
extern _waveInGetErrorTextW@12
export waveInGetErrorTextW@12
extern _waveOutGetDevCapsW@12
export waveOutGetDevCapsW@12
extern _waveOutGetErrorTextW@12
export waveOutGetErrorTextW@12
extern _CreateStdAccessibleProxyW@20
export CreateStdAccessibleProxyW@20
extern _GetRoleTextW@12
export GetRoleTextW@12
extern _GetStateTextW@12
export GetStateTextW@12
extern _OleUIAddVerbMenuW@36
export OleUIAddVerbMenuW@36
extern _OleUIBusyW@4
export OleUIBusyW@4
extern _OleUIChangeIconW@4
export OleUIChangeIconW@4
extern _OleUIChangeSourceW@4
export OleUIChangeSourceW@4
extern _OleUIConvertW@4
export OleUIConvertW@4
extern _OleUIEditLinksW@4
export OleUIEditLinksW@4
extern _OleUIInsertObjectW@4
export OleUIInsertObjectW@4
extern _OleUIObjectPropertiesW@4
export OleUIObjectPropertiesW@4
extern _OleUIPasteSpecialW@4
export OleUIPasteSpecialW@4
extern _OleUIPromptUserW
export OleUIPromptUserW
extern _OleUIUpdateLinksW@16
export OleUIUpdateLinksW@16
extern _AppendMenuW@16
export AppendMenuW@16
extern _BroadcastSystemMessageW@20
export BroadcastSystemMessageW@20
extern _CallMsgFilterW@8
export CallMsgFilterW@8
extern _CallWindowProcA@20
export CallWindowProcA@20
extern _CallWindowProcW@20
export CallWindowProcW@20
extern _ChangeDisplaySettingsExW@20
export ChangeDisplaySettingsExW@20
extern _ChangeDisplaySettingsW@8
export ChangeDisplaySettingsW@8
extern _ChangeMenuW@20
export ChangeMenuW@20
extern _CharLowerBuffW@8
export CharLowerBuffW@8
extern _CharLowerW@4
export CharLowerW@4
extern _CharNextW@4
export CharNextW@4
extern _CharPrevW@8
export CharPrevW@8
extern _CharToOemBuffW@12
export CharToOemBuffW@12
extern _CharToOemW@8
export CharToOemW@8
extern _CharUpperBuffW@8
export CharUpperBuffW@8
extern _CharUpperW@4
export CharUpperW@4
extern _CopyAcceleratorTableW@12
export CopyAcceleratorTableW@12
extern _CreateAcceleratorTableW@8
export CreateAcceleratorTableW@8
extern _CreateDialogIndirectParamW@20
export CreateDialogIndirectParamW@20
extern _CreateDialogParamW@20
export CreateDialogParamW@20
extern _CreateMDIWindowW@40
export CreateMDIWindowW@40
extern _CreateWindowExW@48
export CreateWindowExW@48
extern _DdeConnect@16
export DdeConnect@16
extern _DdeConnectList@20
export DdeConnectList@20
extern _DdeCreateStringHandleW@12
export DdeCreateStringHandleW@12
extern _DdeInitializeW@16
export DdeInitializeW@16
extern _DdeQueryConvInfo@12
export DdeQueryConvInfo@12
extern _DdeQueryStringW@20
export DdeQueryStringW@20
extern _DefDlgProcW@16
export DefDlgProcW@16
extern _DefFrameProcW@20
export DefFrameProcW@20
extern _DefMDIChildProcW@16
export DefMDIChildProcW@16
extern _DefWindowProcW@16
export DefWindowProcW@16
extern _DialogBoxIndirectParamW@20
export DialogBoxIndirectParamW@20
extern _DialogBoxParamW@20
export DialogBoxParamW@20
extern _DispatchMessageW@4
export DispatchMessageW@4
extern _DlgDirListComboBoxW@20
export DlgDirListComboBoxW@20
extern _DlgDirListW@20
export DlgDirListW@20
extern _DlgDirSelectComboBoxExW@16
export DlgDirSelectComboBoxExW@16
extern _DlgDirSelectExW@16
export DlgDirSelectExW@16
extern _DrawStateW@40
export DrawStateW@40
extern _DrawTextExW@24
export DrawTextExW@24
extern _DrawTextW@20
export DrawTextW@20
extern _EnableWindow@8
export EnableWindow@8
extern _EnumClipboardFormats@4
export EnumClipboardFormats@4
extern _EnumDisplayDevicesW@16
export EnumDisplayDevicesW@16
extern _EnumDisplaySettingsExW@16
export EnumDisplaySettingsExW@16
extern _EnumDisplaySettingsW@12
export EnumDisplaySettingsW@12
extern _EnumPropsA@8
export EnumPropsA@8
extern _EnumPropsExA@12
export EnumPropsExA@12
extern _EnumPropsExW@12
export EnumPropsExW@12
extern _EnumPropsW@8
export EnumPropsW@8
extern _FindWindowExW@16
export FindWindowExW@16
extern _FindWindowW@8
export FindWindowW@8
extern _GetAltTabInfoW@20
export GetAltTabInfoW@20
extern _GetClassInfoExW@12
export GetClassInfoExW@12
extern _GetClassInfoW@12
export GetClassInfoW@12
extern _GetClassLongW@8
export GetClassLongW@8
extern _GetClassNameW@12
export GetClassNameW@12
extern _GetClipboardData@4
export GetClipboardData@4
extern _GetClipboardFormatNameW@12
export GetClipboardFormatNameW@12
extern _GetDlgItemTextW@16
export GetDlgItemTextW@16
extern _GetKeyNameTextW@12
export GetKeyNameTextW@12
extern _GetKeyboardLayoutNameW@4
export GetKeyboardLayoutNameW@4
extern _GetMenuItemInfoW@16
export GetMenuItemInfoW@16
extern _GetMenuStringW@20
export GetMenuStringW@20
extern _GetMessageW@16
export GetMessageW@16
extern _GetMonitorInfoW@8
export GetMonitorInfoW@8
extern _GetPropA@8
export GetPropA@8
extern _GetPropW@8
export GetPropW@8
extern _GetTabbedTextExtentW@20
export GetTabbedTextExtentW@20
extern _GetWindowLongA@8
export GetWindowLongA@8
extern _GetWindowLongW@8
export GetWindowLongW@8
extern _GetWindowModuleFileNameW@12
export GetWindowModuleFileNameW@12
extern _GetWindowTextLengthW@4
export GetWindowTextLengthW@4
extern _GetWindowTextW@12
export GetWindowTextW@12
extern _GrayStringW@36
export GrayStringW@36
extern _InsertMenuItemW@16
export InsertMenuItemW@16
extern _InsertMenuW@20
export InsertMenuW@20
extern _IsCharAlphaNumericW@4
export IsCharAlphaNumericW@4
extern _IsCharAlphaW@4
export IsCharAlphaW@4
extern _IsCharLowerW@4
export IsCharLowerW@4
extern _IsCharUpperW@4
export IsCharUpperW@4
extern _IsClipboardFormatAvailable@4
export IsClipboardFormatAvailable@4
extern _IsDialogMessageW@8
export IsDialogMessageW@8
extern _IsWindowUnicode@4
export IsWindowUnicode@4
extern _LoadAcceleratorsW@8
export LoadAcceleratorsW@8
extern _LoadBitmapW@8
export LoadBitmapW@8
extern _LoadCursorFromFileW@4
export LoadCursorFromFileW@4
extern _LoadCursorW@8
export LoadCursorW@8
extern _LoadIconW@8
export LoadIconW@8
extern _LoadImageW@24
export LoadImageW@24
extern _LoadKeyboardLayoutW@8
export LoadKeyboardLayoutW@8
extern _LoadMenuIndirectW@4
export LoadMenuIndirectW@4
extern _LoadMenuW@8
export LoadMenuW@8
extern _LoadStringW@16
export LoadStringW@16
extern _MapVirtualKeyExW@12
export MapVirtualKeyExW@12
extern _MapVirtualKeyW@8
export MapVirtualKeyW@8
extern _MessageBoxExW@20
export MessageBoxExW@20
extern _MessageBoxIndirectW@4
export MessageBoxIndirectW@4
extern _MessageBoxW@16
export MessageBoxW@16
extern _ModifyMenuW@20
export ModifyMenuW@20
extern _OemToCharBuffW@12
export OemToCharBuffW@12
extern _OemToCharW@8
export OemToCharW@8
extern _PeekMessageW@20
export PeekMessageW@20
extern _PostMessageW@16
export PostMessageW@16
extern _PostThreadMessageW@16
export PostThreadMessageW@16
extern _RegisterClassExW@4
export RegisterClassExW@4
extern _RegisterClassW@4
export RegisterClassW@4
extern _RegisterClipboardFormatW@4
export RegisterClipboardFormatW@4
extern _RegisterDeviceNotificationW@12
export RegisterDeviceNotificationW@12
extern _RegisterWindowMessageW@4
export RegisterWindowMessageW@4
extern _RemovePropA@8
export RemovePropA@8
extern _RemovePropW@8
export RemovePropW@8
extern _SendDlgItemMessageW@20
export SendDlgItemMessageW@20
extern _SendMessageCallbackW@24
export SendMessageCallbackW@24
extern _SendMessageTimeoutW@28
export SendMessageTimeoutW@28
extern _SendMessageW@16
export SendMessageW@16
extern _SendNotifyMessageW@16
export SendNotifyMessageW@16
extern _SetClassLongW@12
export SetClassLongW@12
extern _SetDlgItemTextW@12
export SetDlgItemTextW@12
extern _SetMenuItemInfoW@16
export SetMenuItemInfoW@16
extern _SetPropA@12
export SetPropA@12
extern _SetPropW@12
export SetPropW@12
extern _SetWindowLongA@12
export SetWindowLongA@12
extern _SetWindowLongW@12
export SetWindowLongW@12
extern _SetWindowTextW@8
export SetWindowTextW@8
extern _SetWindowsHookExW@16
export SetWindowsHookExW@16
extern _SetWindowsHookW@8
export SetWindowsHookW@8
extern _SystemParametersInfoW@16
export SystemParametersInfoW@16
extern _TabbedTextOutW@32
export TabbedTextOutW@32
extern _TranslateAcceleratorW@12
export TranslateAcceleratorW@12
extern _UnregisterClassW@8
export UnregisterClassW@8
extern _VkKeyScanExW@8
export VkKeyScanExW@8
extern _VkKeyScanW@4
export VkKeyScanW@4
extern _WinHelpW@16
export WinHelpW@16
extern _wsprintfW
export wsprintfW
extern _wvsprintfW@12
export wvsprintfW@12
extern _DragQueryFileW@16
export DragQueryFileW@16
extern _ExtractIconExW@20
export ExtractIconExW@20
extern _ExtractIconW@12
export ExtractIconW@12
extern _FindExecutableW@12
export FindExecutableW@12
extern _SHBrowseForFolderW@4
export SHBrowseForFolderW@4
extern _SHChangeNotify@16
export SHChangeNotify@16
extern _SHFileOperationW@4
export SHFileOperationW@4
extern _SHGetFileInfoW@20
export SHGetFileInfoW@20
extern _SHGetNewLinkInfoW@20
export SHGetNewLinkInfoW@20
extern _SHGetPathFromIDListW@8
export SHGetPathFromIDListW@8
extern _ShellAboutW@16
export ShellAboutW@16
extern _ShellExecuteExW@4
export ShellExecuteExW@4
extern _ShellExecuteW@24
export ShellExecuteW@24
extern _Shell_NotifyIconW@8
export Shell_NotifyIconW@8
extern _GetFileVersionInfoSizeW@8
export GetFileVersionInfoSizeW@8
extern _GetFileVersionInfoW@16
export GetFileVersionInfoW@16
extern _VerFindFileW@32
export VerFindFileW@32
extern _VerInstallFileW@32
export VerInstallFileW@32
extern _VerLanguageNameW@12
export VerLanguageNameW@12
extern _VerQueryValueW@16
export VerQueryValueW@16
extern _CryptAcquireContextW@20
export CryptAcquireContextW@20
extern _CryptEnumProvidersW@24
export CryptEnumProvidersW@24
extern _CryptEnumProviderTypesW@24
export CryptEnumProviderTypesW@24
extern _CryptGetDefaultProviderW@20
export CryptGetDefaultProviderW@20
extern _CryptSetProviderExW@16
export CryptSetProviderExW@16
extern _CryptSetProviderW@8
export CryptSetProviderW@8
extern _CryptSignHashW@24
export CryptSignHashW@24
extern _CryptVerifySignatureW@24
export CryptVerifySignatureW@24
extern _GetCurrentHwProfileW@4
export GetCurrentHwProfileW@4
extern _GetUserNameW@8
export GetUserNameW@8
extern _IsTextUnicode@12
export IsTextUnicode@12
extern _RegConnectRegistryW@12
export RegConnectRegistryW@12
extern _RegCreateKeyExW@36
export RegCreateKeyExW@36
extern _RegCreateKeyW@12
export RegCreateKeyW@12
extern _RegDeleteKeyW@8
export RegDeleteKeyW@8
extern _RegDeleteValueW@8
export RegDeleteValueW@8
extern _RegEnumKeyExW@32
export RegEnumKeyExW@32
extern _RegEnumKeyW@16
export RegEnumKeyW@16
extern _RegEnumValueW@32
export RegEnumValueW@32
extern _RegLoadKeyW@12
export RegLoadKeyW@12
extern _RegOpenKeyExW@20
export RegOpenKeyExW@20
extern _RegOpenKeyW@12
export RegOpenKeyW@12
extern _RegQueryInfoKeyW@48
export RegQueryInfoKeyW@48
extern _RegQueryMultipleValuesW@20
export RegQueryMultipleValuesW@20
extern _RegQueryValueExW@24
export RegQueryValueExW@24
extern _RegQueryValueW@16
export RegQueryValueW@16
extern _RegReplaceKeyW@16
export RegReplaceKeyW@16
extern _RegSaveKeyW@12
export RegSaveKeyW@12
extern _RegSetValueExW@24
export RegSetValueExW@24
extern _RegSetValueW@20
export RegSetValueW@20
extern _RegUnLoadKeyW@8
export RegUnLoadKeyW@8
extern _ChooseColorW@4
export ChooseColorW@4
extern _ChooseFontW@4
export ChooseFontW@4
extern _FindTextW@4
export FindTextW@4
extern _GetFileTitleW@12
export GetFileTitleW@12
extern _GetOpenFileNameW@4
export GetOpenFileNameW@4
extern _GetSaveFileNameW@4
export GetSaveFileNameW@4
extern _PageSetupDlgW@4
export PageSetupDlgW@4
extern _PrintDlgW@4
export PrintDlgW@4
extern _ReplaceTextW@4
export ReplaceTextW@4
extern _AddAtomW@4
export AddAtomW@4
extern _BeginUpdateResourceA@8
export BeginUpdateResourceA@8
extern _BeginUpdateResourceW@8
export BeginUpdateResourceW@8
extern _BuildCommDCBAndTimeoutsW@12
export BuildCommDCBAndTimeoutsW@12
extern _BuildCommDCBW@8
export BuildCommDCBW@8
extern _CallNamedPipeW@28
export CallNamedPipeW@28
extern _CommConfigDialogW@12
export CommConfigDialogW@12
extern _CompareStringW@24
export CompareStringW@24
extern _CopyFileExW@24
export CopyFileExW@24
extern _CopyFileW@12
export CopyFileW@12
extern _CreateDirectoryExW@12
export CreateDirectoryExW@12
extern _CreateDirectoryW@8
export CreateDirectoryW@8
extern _CreateEventW@16
export CreateEventW@16
extern _CreateFileMappingW@24
export CreateFileMappingW@24
extern _CreateFileW@28
export CreateFileW@28
extern _CreateMailslotW@16
export CreateMailslotW@16
extern _CreateMutexW@12
export CreateMutexW@12
extern _CreateNamedPipeW@32
export CreateNamedPipeW@32
extern _CreateProcessW@40
export CreateProcessW@40
extern _CreateSemaphoreW@16
export CreateSemaphoreW@16
extern _CreateWaitableTimerW@12
export CreateWaitableTimerW@12
extern _DeleteFileW@4
export DeleteFileW@4
extern _EndUpdateResourceA@8
export EndUpdateResourceA@8
extern _EndUpdateResourceW@8
export EndUpdateResourceW@8
extern _EnumCalendarInfoExW@16
export EnumCalendarInfoExW@16
extern _EnumCalendarInfoW@16
export EnumCalendarInfoW@16
extern _EnumDateFormatsExW@12
export EnumDateFormatsExW@12
extern _EnumDateFormatsW@12
export EnumDateFormatsW@12
extern _EnumSystemCodePagesW@8
export EnumSystemCodePagesW@8
extern _EnumSystemLocalesW@8
export EnumSystemLocalesW@8
extern _EnumTimeFormatsW@12
export EnumTimeFormatsW@12
extern _ExpandEnvironmentStringsW@12
export ExpandEnvironmentStringsW@12
extern _FatalAppExitW@8
export FatalAppExitW@8
extern _FillConsoleOutputCharacterW@20
export FillConsoleOutputCharacterW@20
extern _FindAtomW@4
export FindAtomW@4
extern _FindFirstChangeNotificationW@12
export FindFirstChangeNotificationW@12
extern _FindFirstFileW@8
export FindFirstFileW@8
extern _FindNextFileW@8
export FindNextFileW@8
extern _FindResourceExW@16
export FindResourceExW@16
extern _FindResourceW@12
export FindResourceW@12
extern _FormatMessageW@28
export FormatMessageW@28
extern _FreeEnvironmentStringsW@4
export FreeEnvironmentStringsW@4
extern _GetAtomNameW@12
export GetAtomNameW@12
extern _GetCPInfo@8
export GetCPInfo@8
extern _GetCPInfoExW@12
export GetCPInfoExW@12
extern _GetCalendarInfoW@24
export GetCalendarInfoW@24
extern _GetComputerNameW@8
export GetComputerNameW@8
extern _GetConsoleTitleW@8
export GetConsoleTitleW@8
extern _GetCurrencyFormatW@24
export GetCurrencyFormatW@24
extern _GetCurrentDirectoryW@8
export GetCurrentDirectoryW@8
extern _GetDateFormatW@24
export GetDateFormatW@24
extern _GetDefaultCommConfigW@12
export GetDefaultCommConfigW@12
extern _GetDiskFreeSpaceExW@16
export GetDiskFreeSpaceExW@16
extern _GetDiskFreeSpaceW@20
export GetDiskFreeSpaceW@20
extern _GetDriveTypeW@4
export GetDriveTypeW@4
extern _GetEnvironmentStringsW@0
export GetEnvironmentStringsW@0
extern _GetEnvironmentVariableW@12
export GetEnvironmentVariableW@12
extern _GetFileAttributesExW@12
export GetFileAttributesExW@12
extern _GetFileAttributesW@4
export GetFileAttributesW@4
extern _GetFullPathNameW@16
export GetFullPathNameW@16
extern _GetLocaleInfoW@16
export GetLocaleInfoW@16
extern _GetLogicalDriveStringsW@8
export GetLogicalDriveStringsW@8
extern _GetLongPathNameW@12
export GetLongPathNameW@12
extern _GetModuleFileNameW@12
export GetModuleFileNameW@12
extern _GetModuleHandleW@4
export GetModuleHandleW@4
extern _GetNamedPipeHandleStateW@28
export GetNamedPipeHandleStateW@28
extern _GetNumberFormatW@24
export GetNumberFormatW@24
extern _GetPrivateProfileIntW@16
export GetPrivateProfileIntW@16
extern _GetPrivateProfileSectionNamesW@12
export GetPrivateProfileSectionNamesW@12
extern _GetPrivateProfileSectionW@16
export GetPrivateProfileSectionW@16
extern _GetPrivateProfileStringW@24
export GetPrivateProfileStringW@24
extern _GetPrivateProfileStructW@20
export GetPrivateProfileStructW@20
extern _GetProcAddress@8
export GetProcAddress@8
extern _GetProfileIntW@12
export GetProfileIntW@12
extern _GetProfileSectionW@12
export GetProfileSectionW@12
extern _GetProfileStringW@20
export GetProfileStringW@20
extern _GetShortPathNameW@12
export GetShortPathNameW@12
extern _GetStartupInfoW@4
export GetStartupInfoW@4
extern _GetStringTypeExW@20
export GetStringTypeExW@20
extern _GetStringTypeW@16
export GetStringTypeW@16
extern _GetSystemDirectoryW@8
export GetSystemDirectoryW@8
extern _GetSystemWindowsDirectoryW@8
export GetSystemWindowsDirectoryW@8
extern _GetTempFileNameW@16
export GetTempFileNameW@16
extern _GetTempPathW@8
export GetTempPathW@8
extern _GetTimeFormatW@24
export GetTimeFormatW@24
extern _GetVersionExW@4
export GetVersionExW@4
extern _GetVolumeInformationW@32
export GetVolumeInformationW@32
extern _GetWindowsDirectoryW@8
export GetWindowsDirectoryW@8
extern _GlobalAddAtomW@4
export GlobalAddAtomW@4
extern _GlobalFindAtomW@4
export GlobalFindAtomW@4
extern _GlobalGetAtomNameW@12
export GlobalGetAtomNameW@12
extern _IsBadStringPtrW@8
export IsBadStringPtrW@8
extern _IsValidCodePage@4
export IsValidCodePage@4
extern _LCMapStringW@24
export LCMapStringW@24
extern _LoadLibraryExW@12
export LoadLibraryExW@12
extern _LoadLibraryW@4
export LoadLibraryW@4
extern _MoveFileW@8
export MoveFileW@8
extern _MultiByteToWideChar@24
export MultiByteToWideChar@24
extern _OpenEventW@12
export OpenEventW@12
extern _OpenFileMappingW@12
export OpenFileMappingW@12
extern _OpenMutexW@12
export OpenMutexW@12
extern _OpenSemaphoreW@12
export OpenSemaphoreW@12
extern _OpenWaitableTimerW@12
export OpenWaitableTimerW@12
extern _OutputDebugStringW@4
export OutputDebugStringW@4
extern _PeekConsoleInputW@16
export PeekConsoleInputW@16
extern _QueryDosDeviceW@12
export QueryDosDeviceW@12
extern _ReadConsoleInputW@16
export ReadConsoleInputW@16
extern _ReadConsoleOutputCharacterW@20
export ReadConsoleOutputCharacterW@20
extern _ReadConsoleOutputW@20
export ReadConsoleOutputW@20
extern _ReadConsoleW@20
export ReadConsoleW@20
extern _RemoveDirectoryW@4
export RemoveDirectoryW@4
extern _ScrollConsoleScreenBufferW@20
export ScrollConsoleScreenBufferW@20
extern _SearchPathW@24
export SearchPathW@24
extern _SetCalendarInfoW@16
export SetCalendarInfoW@16
extern _SetComputerNameW@4
export SetComputerNameW@4
extern _SetConsoleTitleW@4
export SetConsoleTitleW@4
extern _SetCurrentDirectoryW@4
export SetCurrentDirectoryW@4
extern _SetDefaultCommConfigW@12
export SetDefaultCommConfigW@12
extern _SetEnvironmentVariableW@8
export SetEnvironmentVariableW@8
extern _SetFileAttributesW@8
export SetFileAttributesW@8
extern _SetLocaleInfoW@12
export SetLocaleInfoW@12
extern _SetVolumeLabelW@8
export SetVolumeLabelW@8
extern _UpdateResourceA@24
export UpdateResourceA@24
extern _UpdateResourceW@24
export UpdateResourceW@24
extern _WaitNamedPipeW@8
export WaitNamedPipeW@8
extern _WideCharToMultiByte@32
export WideCharToMultiByte@32
extern _WriteConsoleInputW@16
export WriteConsoleInputW@16
extern _WriteConsoleOutputCharacterW@20
export WriteConsoleOutputCharacterW@20
extern _WriteConsoleOutputW@20
export WriteConsoleOutputW@20
extern _WriteConsoleW@20
export WriteConsoleW@20
extern _WritePrivateProfileSectionW@12
export WritePrivateProfileSectionW@12
extern _WritePrivateProfileStringW@16
export WritePrivateProfileStringW@16
extern _WritePrivateProfileStructW@20
export WritePrivateProfileStructW@20
extern _WriteProfileSectionW@8
export WriteProfileSectionW@8
extern _WriteProfileStringW@12
export WriteProfileStringW@12
extern _lstrcatW@8
export lstrcatW@8
extern _lstrcmpW@8
export lstrcmpW@8
extern _lstrcmpiW@8
export lstrcmpiW@8
extern _lstrcpyW@8
export lstrcpyW@8
extern _lstrcpynW@12
export lstrcpynW@12
extern _lstrlenW@4
export lstrlenW@4
extern _RasConnectionNotificationW@12
export RasConnectionNotificationW@12
extern _RasCreatePhonebookEntryW@8
export RasCreatePhonebookEntryW@8
extern _RasDeleteEntryW@8
export RasDeleteEntryW@8
extern _RasDeleteSubEntryW@12
export RasDeleteSubEntryW@12
extern _RasDialW@24
export RasDialW@24
extern _RasEditPhonebookEntryW@12
export RasEditPhonebookEntryW@12
extern _RasEnumConnectionsW@12
export RasEnumConnectionsW@12
extern _RasEnumDevicesW@12
export RasEnumDevicesW@12
extern _RasEnumEntriesW@20
export RasEnumEntriesW@20
extern _RasGetConnectStatusW@8
export RasGetConnectStatusW@8
extern _RasGetEntryDialParamsW@12
export RasGetEntryDialParamsW@12
extern _RasGetEntryPropertiesW@24
export RasGetEntryPropertiesW@24
extern _RasGetErrorStringW@12
export RasGetErrorStringW@12
extern _RasGetProjectionInfoW@16
export RasGetProjectionInfoW@16
extern _RasHangUpW@4
export RasHangUpW@4
extern _RasRenameEntryW@12
export RasRenameEntryW@12
extern _RasSetEntryDialParamsW@12
export RasSetEntryDialParamsW@12
extern _RasSetEntryPropertiesW@24
export RasSetEntryPropertiesW@24
extern _RasSetSubEntryPropertiesW@28
export RasSetSubEntryPropertiesW@28
extern _RasValidateEntryNameW@8
export RasValidateEntryNameW@8
extern _AddJobW@20
export AddJobW@20
extern _AddMonitorW@12
export AddMonitorW@12
extern _AddPortW@12
export AddPortW@12
extern _AddPrintProcessorW@16
export AddPrintProcessorW@16
extern _AddPrintProvidorW@12
export AddPrintProvidorW@12
extern _AddPrinterDriverW@12
export AddPrinterDriverW@12
extern _AddPrinterW@12
export AddPrinterW@12
extern _AdvancedDocumentPropertiesW@20
export AdvancedDocumentPropertiesW@20
extern _ConfigurePortW@12
export ConfigurePortW@12
extern _DeleteMonitorW@12
export DeleteMonitorW@12
extern _DeletePortW@12
export DeletePortW@12
extern _DeletePrintProcessorW@12
export DeletePrintProcessorW@12
extern _DeletePrintProvidorW@12
export DeletePrintProvidorW@12
extern _DeletePrinterDriverW@12
export DeletePrinterDriverW@12
extern _DeviceCapabilitiesW@20
export DeviceCapabilitiesW@20
extern _DocumentPropertiesW@24
export DocumentPropertiesW@24
extern _EnumMonitorsW@24
export EnumMonitorsW@24
extern _EnumPortsW@24
export EnumPortsW@24
extern _EnumPrintProcessorDatatypesW@28
export EnumPrintProcessorDatatypesW@28
extern _EnumPrintProcessorsW@28
export EnumPrintProcessorsW@28
extern _EnumPrinterDriversW@28
export EnumPrinterDriversW@28
extern _EnumPrintersW@28
export EnumPrintersW@28
extern _GetJobW@24
export GetJobW@24
extern _GetPrintProcessorDirectoryW@24
export GetPrintProcessorDirectoryW@24
extern _GetPrinterDataW@24
export GetPrinterDataW@24
extern _GetPrinterDriverDirectoryW@24
export GetPrinterDriverDirectoryW@24
extern _GetPrinterDriverW@24
export GetPrinterDriverW@24
extern _GetPrinterW@20
export GetPrinterW@20
extern _OpenPrinterW@12
export OpenPrinterW@12
extern _ResetPrinterW@8
export ResetPrinterW@8
extern _SetJobW@20
export SetJobW@20
extern _SetPrinterDataW@20
export SetPrinterDataW@20
extern _SetPrinterW@16
export SetPrinterW@16
extern _StartDocPrinterW@12
export StartDocPrinterW@12
extern _GetOpenFileNamePreviewW@4
export GetOpenFileNamePreviewW@4
extern _GetSaveFileNamePreviewW@4
export GetSaveFileNamePreviewW@4
extern _MCIWndCreateW
export MCIWndCreateW
extern _IsDestinationReachableW@8
export IsDestinationReachableW@8
extern _capCreateCaptureWindowW
export capCreateCaptureWindowW
extern _capGetDriverDescriptionW@20
export capGetDriverDescriptionW@20
extern _AcquireCredentialsHandleW@36
export AcquireCredentialsHandleW@36
extern _EnumerateSecurityPackagesW@8
export EnumerateSecurityPackagesW@8
extern _FreeContextBuffer@4
export FreeContextBuffer@4
extern _InitializeSecurityContextW@48
export InitializeSecurityContextW@48
extern _InitSecurityInterfaceW@0
export InitSecurityInterfaceW@0
extern _QueryContextAttributesW@12
export QueryContextAttributesW@12
extern _QueryCredentialsAttributesW@12
export QueryCredentialsAttributesW@12
extern _QuerySecurityPackageInfoW@8
export QuerySecurityPackageInfoW@8
